const ROUTES={"home": "homescreen.webp", "pro": "top-pro.webp", "pro-view": "pro-view.webp", "tempcomp": "tempcomp.webp", "mission": "missionval.webp", "scorecard": "storescorecard.webp", "composite": "composite-over.webp", "operations": "per-qual.webp", "sales-financial": "sales-fin.webp", "people": "people-leader.webp", "storealerts": "storealerts.webp", "alerts": "storealerts.webp", "maximo": "maximo.webp", "production": "production.webp", "replenishment": "replen.webp", "inventory": "inventory.webp", "shrink": "shrink.webp", "sales": "sales.webp", "foodsafety": "foodsafety.webp", "safety": "safety.webp", "labor": "labor.webp", "labor-health": "laborsnap.webp", "ordering": "orderman.webp", "compliance": "compsnap.webp", "associate-home": "assoc-dept-home.webp", "experience-1": "temp1.webp", "experience-2": "temp2.webp", "experience-3": "temp3.webp", "experience-4": "temp4.webp", "experience-5": "temp5.webp", "experience-6": "temp6.webp", "grocery-1": "assoc-gro1.webp", "grocery-2": "assoc-groc2.webp", "produce-1": "assoc-prod1.webp", "produce-2": "assoc-prod2.webp", "dairy-1": "assoc-dairy1.webp", "dairy-2": "assoc-dairy2.webp", "frozen-1": "assoc-froz1.webp", "frozen-2": "assoc-froz2.webp", "meat-1": "assoc-meat1.webp", "meat-2": "assoc-meat2.webp", "seafood-1": "assoc-sea1.webp", "seafood-2": "assoc-sea2.webp", "deli-1": "assoc-deli1.webp", "deli-2": "assoc-deli2.webp", "bakery-1": "assoc-bak1.webp", "bakery-2": "assoc-bak2.webp", "starbucks-1": "assoc-star1.webp", "starbucks-2": "assoc-star2.webp", "murrays-1": "assoc.mur1.webp", "murrays-2": "assoc-mur2.webp", "front-end-1": "assoc-front1.webp", "front-end-2": "assoc-front2.webp", "ecommerce-1": "assoc-ecom.webp", "ecommerce-2": "assoc-ecom2.webp", "general-merchandise-1": "assoc-gm1.webp", "general-merchandise-2": "assoc-gm2.webp", "hbc-1": "assoc-hbc1.webp", "hbc-2": "assoc-hbc2.webp", "liquor-1": "assoc-liq1.webp", "liquor-2": "assoc-liq2.webp", "receiving-1": "assoc-rec1.webp", "receiving-2": "assoc-rec2.webp", "home-department-1": "assoc-home1.webp", "home-department-2": "assoc-home2.webp", "management-1": "assoc-man1.webp", "management-2": "assoc-man2.webp"};
const NEXT={"grocery-1": "grocery-2", "produce-1": "produce-2", "dairy-1": "dairy-2", "frozen-1": "frozen-2", "meat-1": "meat-2", "seafood-1": "seafood-2", "deli-1": "deli-2", "bakery-1": "bakery-2", "starbucks-1": "starbucks-2", "murrays-1": "murrays-2", "front-end-1": "front-end-2", "ecommerce-1": "ecommerce-2", "general-merchandise-1": "general-merchandise-2", "hbc-1": "hbc-2", "liquor-1": "liquor-2", "receiving-1": "receiving-2", "home-department-1": "home-department-2", "management-1": "management-2", "experience-1": "experience-2", "experience-2": "experience-3", "experience-3": "experience-4", "experience-4": "experience-5", "experience-5": "experience-6"};
const DEPTS=["grocery", "produce", "dairy", "frozen", "meat", "seafood", "deli", "bakery", "starbucks", "murrays", "front-end", "ecommerce", "general-merchandise", "hbc", "liquor", "receiving", "home-department", "management"];
const app=document.querySelector('#app'), toast=document.querySelector('#toast'), dialog=document.querySelector('#assistant'), chat=document.querySelector('#chat'), input=document.querySelector('#assistant-input');
let current='home'; const DEBUG=new URLSearchParams(location.search).has('debug');
function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function go(id,push=true){if(!ROUTES[id]){say('Screen not found: '+id);return} current=id;if(push)history.pushState({id},'', '#'+id);render()}
function back(){if(history.length>1)history.back();else go('home')}
function forward(){go(NEXT[current]||'home')}
window.addEventListener('popstate',e=>{current=(e.state&&e.state.id)||location.hash.slice(1)||'home';render()})
function hs(label,x,y,w,h,action){return {label,x,y,w,h,action}}
function globalHotspots(){return [hs('Back',.055,.095,.12,.055,back),hs('Forward',.72,.095,.11,.055,forward),hs('Alerts',.84,.09,.11,.07,()=>go('alerts')),hs('Home',.08,.90,.19,.075,()=>go('home')),hs('AI Assistant',.27,.90,.22,.075,openAssistant),hs('Voice Search',.49,.90,.21,.075,startVoice),hs('Alerts',.71,.90,.20,.075,()=>go('alerts'))]}
function homeHotspots(){let a=[];let ys=[.247,.279,.311,.343],ids=['pro','pro-view','tempcomp','mission'];ys.forEach((y,i)=>a.push(hs(ids[i],.37,y,.49,.032,()=>go(ids[i]))));
[['scorecard',.10,.414],['composite',.365,.414],['maximo',.63,.414],['tempcomp',.10,.536],['sales',.365,.536],['labor-health',.63,.536]].forEach(([id,x,y])=>a.push(hs(id,x,y,.25,.112,()=>go(id))));
let r1=['production','replenishment','inventory','shrink','sales','foodsafety'];r1.forEach((id,i)=>a.push(hs(id,.10+i*.13,.684,.12,.068,()=>go(id))));
let r2=[['safety',.10,.758,.14],['labor',.25,.758,.14],['ordering',.40,.758,.14],['associate-home',.55,.758,.18],['compliance',.74,.758,.15]];r2.forEach(([id,x,y,w])=>a.push(hs(id,x,y,w,.068,()=>go(id))));
a.push(hs('Associate Experience',.10,.835,.79,.058,()=>go('experience-1')));a.push(hs('Home',.08,.905,.19,.07,()=>go('home')),hs('AI Assistant',.27,.905,.22,.07,openAssistant),hs('Voice Search',.49,.905,.21,.07,startVoice),hs('Alerts',.71,.905,.20,.07,()=>go('alerts')));a.push(hs('Top Alerts',.70,.125,.10,.06,()=>go('alerts')));return a}
function compositeHotspots(){return [hs('Sales & Financial',.09,.755,.20,.12,()=>go('sales-financial')),hs('Operations & Quality',.30,.755,.20,.12,()=>go('operations')),hs('People & Leadership',.51,.755,.20,.12,()=>go('people')),hs('Alerts & Risks',.72,.755,.18,.12,()=>go('storealerts'))]}
function deptHotspots(){let visible=['grocery','produce','dairy','frozen','meat','seafood','deli','bakery','starbucks','murrays','front-end','ecommerce','general-merchandise','hbc','liquor','receiving','management'];let a=[];let y0=.173,h=.047;visible.forEach((d,i)=>a.push(hs(d,.07,y0+i*h,.84,h*.94,()=>go(d+'-1'))));return a}
function render(){app.innerHTML='<div class="loading">Loading…</div>';let wrap=document.createElement('div');wrap.className='screen';let img=new Image();img.alt=current;img.src='images/'+ROUTES[current];img.onload=()=>{wrap.innerHTML='';wrap.appendChild(img);let layer=document.createElement('div');layer.className='hotspot-layer';let specs=current==='home'?homeHotspots():globalHotspots();if(current==='composite')specs=specs.concat(compositeHotspots());if(current==='associate-home')specs=specs.concat(deptHotspots());specs.forEach(s=>{let b=document.createElement('button');b.className='hotspot'+(DEBUG?' debug':'');b.ariaLabel=s.label;b.title=s.label;b.style.cssText=`left:${s.x*100}%;top:${s.y*100}%;width:${s.w*100}%;height:${s.h*100}%`;if(DEBUG)b.textContent=s.label;b.onclick=e=>{e.preventDefault();s.action()};layer.appendChild(b)});wrap.appendChild(layer);app.replaceChildren(wrap)};img.onerror=()=>{app.textContent='Missing image: '+ROUTES[current]}}
function normalize(t){return t.toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^(open|show|go to|take me to|find) /,'')}
const ALIASES={'home':'home','dashboard':'home','pro':'pro','pro view':'pro-view','temperature compliance':'tempcomp','mission value':'mission','store scorecard':'scorecard','composite':'composite','operations and quality':'operations','sales and financial':'sales-financial','people and leadership':'people','alerts and risks':'storealerts','store alerts':'storealerts','maximo':'maximo','production':'production','replenishment':'replenishment','inventory':'inventory','shrink':'shrink','sales':'sales','food safety':'foodsafety','safety':'safety','labor':'labor','labor health':'labor-health','ordering':'ordering','compliance':'compliance','associate department':'associate-home','associate experience':'experience-1','temperature experience':'experience-1','alerts':'alerts'};DEPTS.forEach(d=>ALIASES[d.replaceAll('-',' ')]=d+'-1');
function match(t){let n=normalize(t);if(ALIASES[n])return ALIASES[n];for(const [k,v] of Object.entries(ALIASES))if(n.includes(k))return v;return null}
function handleText(t){let id=match(t);chat.insertAdjacentHTML('beforeend','<p><b>You:</b> '+escapeHtml(t)+'</p>');if(id){chat.insertAdjacentHTML('beforeend','<p><b>FRIEND:</b> Opening '+escapeHtml(nice(id))+'.</p>');go(id);dialog.close()}else chat.insertAdjacentHTML('beforeend','<p><b>FRIEND:</b> Try “Open Production,” “Open Store Scorecard,” or “Open Bakery.”</p>');chat.scrollTop=chat.scrollHeight}
function nice(id){return id.replace(/-1$/,'').replaceAll('-',' ')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openAssistant(){dialog.showModal();setTimeout(()=>input.focus(),50)}
document.querySelector('#assistant-form').onsubmit=e=>{e.preventDefault();let t=input.value.trim();if(t)handleText(t);input.value=''};document.querySelector('#assistant-mic').onclick=startVoice;
function startVoice(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){openAssistant();say('Voice recognition is unavailable here. Type your request.');return}let r=new SR();r.lang='en-US';r.interimResults=false;r.onstart=()=>say('Listening…');r.onresult=e=>{let t=e.results[0][0].transcript;say(t);let id=match(t);if(id)go(id);else{openAssistant();handleText(t)}};r.onerror=e=>say('Microphone: '+e.error);r.start()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
current=location.hash.slice(1)||'home';history.replaceState({id:current},'', '#'+current);render();
